services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: learning_platform_sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=LearningPlatform@2026
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:alpine
    container_name: learning_platform_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mssql_data:
  redis_data:
